<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Label
 */
?>
<?php
    if (Mage::getStoreConfig('amlabel/options/use_js')) :
?>
        <script type="text/javascript">
            var amlabel_selector = '<?php echo Mage::getStoreConfig('amlabel/options/selector')?>';
            <?php echo Mage::registry('amlabel_scripts');?>
        </script>
<?php
    endif;
?>

