<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @version    2.5.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="content-header">
    <h3><?php echo Mage::helper('adminhtml')->__('MailChimp synchronization') ?></h3>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getSyncToMailchimpUrl()?>')" type="button" class="scalable"><span><?php echo Mage::helper('adminhtml')->__('Sync to MailChimp') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Opens new window with synchronization options')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getSyncFromMailchimpUrl()?>')" type="button" class="scalable"><span><?php echo Mage::helper('adminhtml')->__('Sync from MailChimp') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Opens new window with synchronization options')?>
        </td>
    </tr>
</table>
<div class="content-header">
    <h3><?php echo Mage::helper('adminhtml')->__('Synchronization with Magento newsletter') ?></h3>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getImportNewsletterTemplatesUrl()?>')" type="button" class="scalable"><span><?php echo Mage::helper('adminhtml')->__('Import Templates') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Imports templates from Magento newsletter to Advanced Newsletter')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getImportNewsletterSubscribersUrl()?>')" type="button" class="scalable"><span><?php echo Mage::helper('adminhtml')->__('Import Subscribers') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Imports subscribers from Magento newsletter to Advanced Newsletter')?>
        </td>
    </tr>
</table>