<?php
    $_productCollection = $this->getProductCollection();
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<?php
	$_collectionSize = $_productCollection->count();
	$_columnsCount = $this->getColumnsCount();
	$_qsHelper = $this->helper('quickshop');
	$_imgHelper = $this->helper('catalog/image');
	$_ftHelper = $this->helper('filterproducts');
    $_helper = $this->helper('catalog/output');
	$_uniqId = uniqid('grid');
	$options = $this->getData();
	$curPage = (int)$this->getCurPage();
	$_limit = (int)$this->getLimit();
	$wlHelper = $this->helper('wishlist');
	$_width = $options['thumb_width']; $_height = $options['thumb_height'];
	$_imgHelper = $this->helper('catalog/image');
	if($_qsEnable = Mage::helper('core')->isModuleEnabled('Codazon_Quickshop')){
		$qsHelper = $this->helper('quickshop');	
	}
	$_storeId = Mage::app()->getStore()->getId();
?>
<div class="codazon-filter codazon-filter-style-09 cdz-block-product01 <?php echo $options['custom_class'] ?>" id="<?php echo $_uniqId ?>">
	<div class="products-grid"> 
    <div class="product-items">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
    	<?php if($i%$_columnsCount == 0): ?>
    	<ul class="item-group">
    	<?php endif ?>
            <li class="item product-item cdz-col-<?php echo (string)($i%$_columnsCount + 1) ?>">
				<div class="product-item-info">
				<div class="cdz-hover-section">
					<div class="cdz-product-top">
                    <?php if( $this->display('image') ):?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $_imgHelper->init($_product, 'small_image')->resize($_width,$_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    <img src="<?php echo (string)$_imgHelper->init($_product,'thumbnail')->resize($_width, $_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" class="alternative-img img-responsive" />
                    </a>
                    <?php endif ?>
                    </div>
                    <?php if( $this->display('label') ) echo $_ftHelper->getProductLabel($_product) ?>
                    <?php if($_qsEnable): ?>
                    <div class="qs-button-icon">
						<?php echo $qsHelper->getQuickshopHtml($_product) ?>
                    </div>
                    <?php endif ?>
                </div>
				
                <div class="product-item-details">
					<?php if( $this->display('name') ):?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php endif ?>
                    
                    <?php if ( $this->display('description') ):
					$desc = $this->stripTags($_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description'));
					if(strlen($desc)>80) {
						$strCutTitle = substr($desc, 0, 80);
						$desc = substr($strCutTitle, 0, strrpos($strCutTitle, ' '))."&hellip;";
					}
					?>
					<div class="desc product-item-description"><?php echo $desc; ?></div>
                    <?php endif ;?>
                    
                    
                    <?php if( $this->display('price') ):?>
						<?php echo $this->getPriceHtml($_product, true, $_uniqId) ?>
                    <?php endif ?>
					<?php if( $this->display('rating') ):?>
						<?php //if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php //endif; ?>
                    <?php endif; ?>
                    <div class="cdz-product-bottom">
						<div class="cdz-buttons-container">
                        	<div class="cdz-buttons-inner">
                        		<div class="cart-wrapper">
                                <?php if( $this->display('addtocart_btn') ):?>
                                    <?php if($_product->isSaleable()): ?>
                                    <div class="cart-qty">
                                        <div class="qty-ctl">
                                            <button title="decrease" onclick="changeCartQty(this,-1); return false;" class="decrease">decrease</button>
                                        </div>
                                        <input type="text" name="qty" maxlength="12" value="1" title="Qty" class="input-text qty">
                                        <div class="qty-ctl">
                                            <button title="increase" onclick="changeCartQty(this,1); return false;" class="increase">increase</button>
                                        </div>
                                    </div>
                                    <button data-toggle="tooltip" data-original-title="<?php echo $this->__('Add to Cart') ?>" type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart"
                                        onclick="setLocation('<?php echo $this->getAddToCartUrl($_product,array('has_qty' => 1)) ?>')"
                                    ><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
									<?php endif; ?>
                                <?php endif ?>
								<?php if( $this->display('wishlist_btn') ):?>
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <div class="actions-secondary" ><a data-toggle="tooltip" title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="action link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></div>
                                    <?php endif; ?>
									
                                <?php endif ?>
                                </div>
                            </div>
                        </div>
					</div>
                </div>
				</div>
            </li>
        <?php $i++; ?>
        <?php if( ($i%$_columnsCount == 0) or ($i==$_collectionSize)): ?>
            </ul>
        <?php endif ?>
        <?php endforeach ?>
		</div>
	</div>
</div>
<?php if(  $options['use_slider'] == 1 ): ?>
<script type="text/javascript">
	(function($){
	<?php if( !empty( $options['after_load'] ) and ($options['after_load'] == 1) ): ?>
	$(document).ready(function(e) {
	<?php endif ?>
		var $wrapper = $('#<?php echo $_uniqId ?>');
        var $owl = $('.product-items',$wrapper);
		$owl.addClass('owl-carousel owl-theme');
		$owl.owlCarousel({
			autoplay:	<?php echo (  $options['auto_play'] == 1 )?'true':'false'; ?>,
			autoplayTimeout: 5000,
			smartSpeed:	250,
			loop: <?php echo (  $options['loop'] == 1 )?'true':'false'; ?>,
			responsiveClass:true,
			nav: <?php echo (  $options['show_nav'] == 1 )?'true':'false'; ?>,
			navText: ['Prev','Next'],
			fluidSpeed: true,
			responsive:{
				0:{items: <?php echo $options['items_0'] ?>},
				320:{items:	<?php echo $options['items_320'] ?>},
				480:{items:	<?php echo $options['items_480'] ?>},
				768:{items:	<?php echo $options['items_768'] ?>},
				1024:{items: <?php echo $options['items_1024'] ?>},
				1280:{items: <?php echo $options['items_1280'] ?>}
			},
			margin: <?php echo $options['margin'] ?>,
			center:	false,
			dots: <?php echo (  $options['show_dots'] == 1 )?'true':'false'; ?>
		});
		var makeSameHeight = function(){
			$wrapper.sameHeightItems({
				parent: '.product-items',
				sItem: '.product-item-details'
			});
		};
		$wrapper.find('.product-image').last().find('img').last().each(function(){
			if (this.complete) {
				makeSameHeight();
			}else{
				$(this).on('load.setMaxHeight',function(){
					makeSameHeight();
					$(this).off('load.setMaxHeight');
				});
			}
		});
		var timeout = false;
		$(window).resize(function(){
			if(timeout) clearTimeout(timeout);
			timeout = setTimeout(makeSameHeight,500);
		});
    <?php if( !empty( $options['after_load'] ) and ($options['after_load'] == 1) ): ?>
	});
	<?php endif ?>
	})(jQuery);
</script>
<?php endif ?>

<?php endif; ?>