<?php
    $_productCollection = $this->getProductCollection();
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<?php
	$_collectionSize = $_productCollection->count();
	$_qsHelper = $this->helper('quickshop');
	$_helper = $this->helper('catalog/output');
	$_uniqId = uniqid('grid');
	$options = $this->getDataArray();
	$wlHelper = $this->helper('wishlist');
	$_qsHelper = $this->helper('quickshop');
	$_width = $options['thumb_height']; $_height = $options['thumb_height'];
	$_imgHelper = $this->helper('catalog/image');
	$placeHolder = $_imgHelper->init(Mage::getModel('catalog/product'), 'small_image')->resize($_width, $_height);
	$_ftHelper = $this->helper('filterproducts');
	
?>
<div class="category-products codazon-filter codazon-list-style-02  cdz-block-product01 <?php echo $options['custom_class'] ?>" id="<?php echo $_uniqId ?>">
	<div class="products-list"> 
    <ul class="product-items">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
            <li class="item product-item" style="min-height:auto;">
				<div class="product-item-info">
                    <div class="cdz-product-left">
                    <?php if( $this->display('image') ):?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
					<img width="<?php echo $_width ?>" height="<?php echo $_height ?>" src="<?php echo $placeHolder ?>" class="img-responsive cdz-lazy" data-src="<?php echo $_imgHelper->init($_product, 'small_image')->resize($_width,$_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
					<img width="<?php echo $_width ?>" height="<?php echo $_height ?>" src="<?php echo $placeHolder ?>" data-src="<?php echo (string)$_imgHelper->init($_product, 'thumbnail')->resize($_width,$_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" class="cdz-lazy alternative-img img-responsive"  />
					</a>
                    <a href="javascript:void(0)" class="qs-button" data-url="<?php echo $this->getUrl('quickshop/index/view',array('id' => $_product->getId())) ?>" data-toggle="modal" data-target="#cdz-qsiframe"><?php echo $this->__('Quick shop') ?></a>
                    <?php endif ?>
                    <?php if( $this->display('label') ) echo $_ftHelper->getProductLabel($_product) ?>
                    </div>

                    <div class="cdz-product-right">
                    	<div class="product-item-details">
							<?php if( $this->display('name') ):?>
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                            <?php endif ?>
                            
                            <?php if ( $this->display('description') ):
                            $desc = $this->stripTags($_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description'));
                            if(strlen($desc)>80) {
                                $strCutTitle = substr($desc, 0, 80);
                                $desc = substr($strCutTitle, 0, strrpos($strCutTitle, ' '))."&hellip;";
                            }
                            ?>
                            <div class="desc product-item-description"><?php echo $desc; ?></div>
                            <?php endif ;?>
                            
                            
                            <?php if( $this->display('price') ):?>
                                <?php echo $this->getPriceHtml($_product, true, $_uniqId) ?>
                            <?php endif ?>
                            <?php if( $this->display('rating') ):?>
                                <?php if($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                        <div class="cdz-product-bottom">
                            <div class="cdz-buttons-container">
                                <div class="cdz-buttons-inner">
                                    <div class="cart-wrapper">
                                    <?php if( $this->display('addtocart_btn') ):?>
                                        <?php if($_product->isSaleable()): ?>
                                        <div class="cart-qty">
                                            <div class="qty-ctl">
                                                <button title="decrease" onclick="changeCartQty(this,-1); return false;" class="decrease">decrease</button>
                                            </div>
                                            <input type="text" name="qty" maxlength="12" value="1" title="Qty" class="input-text qty">
                                            <div class="qty-ctl">
                                                <button title="increase" onclick="changeCartQty(this,1); return false;" class="increase">increase</button>
                                            </div>
                                        </div>
                                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart"
                                            onclick="setLocation('<?php echo $this->getAddToCartUrl($_product,array('has_qty' => 1)) ?>')"
                                        ><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                        <?php endif; ?>
                                    <?php endif ?>
                                    <?php if( $this->display('wishlist_btn') ):?>
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <div class="actions-secondary" ><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="action link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></div>
                                        <?php endif; ?>
                                    <?php endif ?>
                                    </div>
                                </div>
                            </div>
						</div>
                    </div>
				</div>
            </li>
        <?php $i++; ?>
        <?php endforeach ?>
		</ul>
	</div>
</div>
<?php endif; ?>