<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @version    2.5.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="entry-edit">
    <h4><?php echo $this->__('Subscriptions') ?></h4>
    <input type="hidden" id="an_segment_changed" name="an_segments_changed" value="0" />
    <?php foreach ($this->getSegments() as $segment): ?>
    <div class="an-segments-block">
        <input onclick="$('an_segment_changed').value = 1" <?php if ($this->isChecked($segment)): ?> checked="checked" <?php endif; ?> type="checkbox" class="an_segments_check" value="<?php echo $segment->getCode(); ?>" id="<?php echo $segment->getCode(); ?>" name="segments_codes[]" />
        <label for="<?php echo $segment->getCode(); ?>"><?php echo $segment->getTitle(); ?></label>
    </div>
    <?php endforeach; ?>
</div>
<div style="clear:both"></div>
<?php echo $this->getChildHtml('grid') ?>
