<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Sarbacane
 * @package     Sarbacane_Sarbacanedesktop
 * @author      Sarbacane Software <contact@sarbacane.com>
 * @copyright   2015 Sarbacane Software
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
$key_for_synchronisation = $this->getKeyForSynchronisation ();
$list_configuration = $this->getListConfiguration ();
$general_configuration = $this->getGeneralConfiguration ();
$stores_array = $this->getStoresArray ();
?>
<link rel="stylesheet" type="text/css" href="<?=$this->getSkinUrl('css/Sarbacane_SarbacaneDesktop/sarbacanedesktop.css')?>" />
<script type="text/javascript" src="<?=$this->getSkinUrl('js/Sarbacane_SarbacaneDesktop/sarbacanedesktop.js')?>"></script>
<div id="sarbacanedesktop">
	<div class="sd_header">
		<div class="sd_logo_<?=$this->__('sarbacane') ?>"></div>
	</div>
	<p class="sd_title"><?=$this->__('It\'s easy to manage your newsletter and email campaigns')?></p>
	<div class="sd_title_separator_page"></div>
	<div class="sd_video_config_container">
		<div class="sd_video_container">
			<iframe width="565" height="315" src="<?=$this->__('https://www.youtube.com/embed/eLMy2tSSYgE')?>?rel=0&showinfo=0" frameborder="0" allowfullscreen></iframe>
		</div>
		<div class="sd_config_container">
			<p><?=$this->__('This Magento module enables you to synchronize clients and accounts that have subscribed to your newsletter from your shop online using Sarbacane Desktop\'s email marketing software.')?></p>
			<p>
				<input type="button" onclick="document.location = '#sd_step'" class="sd_config_button" value="<?=$this->__('Begin the set-up')?>" />
			</p>
		</div>
	</div>
	<div class="sd_separator"></div>
	<div class="sd_detail_description_container">
		<div>
			<div>
				<div>
					<div class="sd_picto1"></div>
					<p class="sd_long_subtitle"><?=$this->__('Synchronization of your shop data')?></p>
				</div>
			</div>
			<div>
				<div>
					<div class="sd_picto2"></div>
					<p class="sd_long_subtitle"><?=$this->__('Responsive visual editor')?></p>
				</div>
			</div>
			<div>
				<div>
					<div class="sd_picto3"></div>
					<p class="sd_short_subtitle"><?=$this->__('Detailed statistics')?></p>
				</div>
			</div>
			<div>
				<div>
					<div class="sd_picto4"></div>
					<p class="sd_short_subtitle"><?=$this->__('Optimal deliverability')?></p>
				</div>
			</div>
		</div>
		<div>
			<div>
				<div>
					<div class="sd_subtitle_separator"></div>
					<p><?=$this->__('Synchronize and manage all the email lists from your Magento store')?></p>
				</div>
			</div>
			<div>
				<div>
					<div class="sd_subtitle_separator"></div>
					<p><?=$this->__('NEW! Create awesome, responsive newsletters thanks to the EmailBuilder')?></p>
				</div>
			</div>
			<div>
				<div>
					<div class="sd_subtitle_separator"></div>
					<p><?=$this->__('Geolocation, openings, opening time, clicks, opt-outs...')?></p>
				</div>
			</div>
			<div>
				<div>
					<div class="sd_subtitle_separator"></div>
					<p><?=$this->__('Optimal deliverability thanks to our renowned professional routing platform')?></p>
				</div>
			</div>
		</div>
	</div>
	<div class="sd_separator"></div>
	<div class="sd_account_offer_container">
		<p class="sd_account"><?=$this->__('Create your account for free and start sending emails')?></p>
		<p class="sd_offer"><?=$this->__('No strings attached')?></p>
		<div class="sd_title_separator_account_offer"></div>
	</div>
	<div class="sd_info_container">
		<div class="sd_info_container_left">
			<div>
				<p class="sd_info_title"><?=$this->__('Why choose Sarbacane?')?></p>
				<div>
					<p><?=$this->__('Create your account for free and start sending emails')?></p>
					<p><?=$this->__('Trusted by over 20,000 users worldwide.')?></p>
					<p><?=$this->__('Awarded Best Emailing Solution by Bsoco Awards (an index that compares emailing solutions)')?></p>
					<p><?=$this->__('All you need to succeed: design, customize, send, and follow-up on your campaigns')?></p>
					<p><?=$this->__('A tech heldpdesk and a variety of resources to help: videos, tutorials, manuals, tips...')?></p>
				</div>
			</div>
		</div>
		<div class="sd_info_container_right">
			<div>
				<p class="sd_info_title"><?=$this->__('Need help?')?></p>
				<div>
					<p><?=$this->__('Email:')?>  <?=$this->__('support@sarbacane.com')?></p>
					<p><?=$this->__('Tel:')?> <?=$this->__('+33(0) 328 328 040')?></p>
					<p>
						<?=$this->__('Website:')?>
						<a href="<?=$this->__('http://www.sarbacane.com/?utm_source=module-magento&utm_medium=plugin&utm_content=lien-sarbacane&utm_campaign=magento')?>" target="_blank"><?=$this->__('http://www.sarbacane.com')?></a>
					</p>
				</div>
			</div>
		</div>
	</div>
	<div id="sd_step"></div>
	<!-- ETAPE 1 -->
	<div id="sd_step1" class="sd_step <?php if(Mage::getSingleton("core/session")->getData("sd_is_user") == null && $general_configuration<2){?>sd_show_step<?php }?>">
		<p class="sd_step_title"><?=$this->__('How to set up the module?')?></p>
		<div class="sd_step_line"></div>
		<p class="sd_step1_instruction"><?=$this->__('Do you already have a Sarbacane Desktop account?')?></p>
		<form autocomplete="off" action="<?= Mage::helper('adminhtml')->getUrl("*/*/*/"); ?>#sd_step" method="post">
			<p class="sd_step1_selection">
				<span> <input onclick="sdUserYesNoDisplayButton('yes')" type="radio" id="sd_user_click_yes" name="sd_is_user" value="yes" <?php if(Mage::getSingleton("core/session")->getData("sd_is_user") == "yes"){?>checked="checked"<?php }?>/> <label for="sd_user_click_yes"><?=$this->__('Yes')?></label>
				</span> <span> <input onclick="sdUserYesNoDisplayButton('no')" type="radio" id="sd_user_click_no" name="sd_is_user" value="no" /> <label for="sd_user_click_no" <?php if(Mage::getSingleton("core/session")->getData("sd_is_user") == "no"){?>checked="checked"<?php }?>><?=$this->__('No')?></label>
				</span>
			</p>
			<div class="sd_step_buttons">
				<div class="sd_step_buttons_right">
					<input type="hidden" name="submit_is_user" value="1" /> <input type="hidden" name="form_key" value="<?= $this->getFormKey()?>" /> <input type="submit" class="sd_button" value="<?=$this->__('Next')?>" />
				</div>
			</div>
		</form>
	</div>

	<!-- ETAPE 2 -->
	<div id="sd_step2" class="sd_step <?php if((Mage::getSingleton("core/session")->getData("sd_is_user") == "yes" || Mage::getSingleton("core/session")->getData("sd_is_user") == "no") && $general_configuration<2 ){?>sd_show_step<?php }?>">
		<div class="sd_step_line"></div>
		<p class="sd_step2_instruction"><?=$this->__('Select your shop and pick your settings')?></p>
		<form autocomplete="off" action="<?= Mage::helper('adminhtml')->getUrl("*/*/*/"); ?>#sd_step" method="post">
			<div class="sd_step2_selection">
			<?php foreach ($stores_array as $store){?>
			
				<div class="sd_step2_selection_list">
					<p class="sd_step2_selection_shop_title"><?=$store['store_name']?></p>
					<div class="sd_step2_selection_shop">
						<div class="sd_step2_selection_shop_input">
							<input type="checkbox" name="store_id[]" value="<?=$store['store_id']?>N0" <?php if(in_array($store['store_id']+"N0",$list_configuration)){?>checked="checked"<?php }?> />&nbsp;
						</div>
						<div class="sd_step2_selection_shop_text">
							<?=$this->__('Create a list in Sarbacane Desktop with newsletter opt-ins')?>
						</div>
					</div>
					<div class="sd_step2_selection_shop">
						<div class="sd_step2_selection_shop_input">
						<?php 
							$storeValue = "";
							$storeChecked = false;
							$storeWithCustomersData=false;
							if(in_array($store['store_id']."C1", $list_configuration)){
								$storeValue = $store['store_id'].'C1';
								$storeWithCustomersData=true;
								$storeChecked = true;
							}else if(in_array($store['store_id']."C0", $list_configuration)){
								$storeValue = $store['store_id']."C0";
								$storeChecked = true;
							}
								
						?>
							<input id="id_shop_<?=$store['store_id']?>C" type="checkbox" name="store_id[]" onclick="changeOptionOrdersDataDisplay('<?=$store['store_id']?>C', this.checked)" value="<?=$storeValue?>" <?php if($storeChecked){ ?>checked="checked"<?php }?>/>&nbsp;
						</div>
						<div class="sd_step2_selection_shop_text">
							<?=$this->__('Create a list in Sarbacane Desktop with your clients who have an account or who have placed an order online')?>
						</div>
					</div>
					<div class="sd_step2_selection_shop_option">
						<div class="sd_step2_selection_shop_input">
							<input id="customer_data_<?=$store['store_id']?>C" type="checkbox" onclick="changeOptionOrdersData('<?=$store['store_id']?>C', this.checked)" value="<?php if($storeWithCustomersData){ echo $store['store_id'].'C1';} ?>" <?php if($storeWithCustomersData){?>checked="checked"<?php }?> />&nbsp;
						</div>
						<div class="sd_step2_selection_shop_text">
							<?=$this->__('Add order data (date, amount, etc...)')?>
						</div>
						<div onclick="sdInfoDataOrdersClick('<?=$store['store_id']?>C')" onmouseover="sdInfoDataOrdersHover('<?=$store['store_id']?>C')" onmouseout="sdInfoDataOrdersOut('<?=$store['store_id']?>C')" class="sd_step2_info"></div>
					</div>
				</div>
				<div id="sd_tooltip_<?=$store['store_id']?>C" class="sd_tooltip">
					<div>
						<?=$this->__('As you enable data from orders, you can also gather extra info in your contact list, and target your recipients in Sarbacane Desktop.')?>
						<br /><?=$this->__('Below are pieces of information that will be added to your contact list:')?>
						<br /><?=$this->__('- Date of first order')?>
						<br /><?=$this->__('- Date of latest order')?>
						<br /><?=$this->__('- Total number of orders')?>
						<br /><?=$this->__('- Total amount of orders')?>
						<br /><?=$this->__('- Amount of the cheapest order')?>
						<br /><?=$this->__('- Amount of the most expensive order')?>
						<br /><?=$this->__('- Average amount of the orders placed')?>
					</div>
				</div>
				<?php }?>
			</div>
			<div class="sd_step_buttons">
				<div class="sd_step_buttons_left">
					<input type="button" onclick="sdDisplayStep(1)" value="<?=$this->__('Previous')?>" />
				</div>
				<div class="sd_step_buttons_right">
					<input type="hidden" name="submit_configuration" value="1" /> <input type="hidden" name="submit_is_user" value="<?=$this->getIsUser()?>" /> <input type="hidden" name="form_key" value="<?= $this->getFormKey()?>" /> <input type="submit" class="sd_button" value="<?=$this->__('Next')?>" />
				</div>
			</div>
		</form>
	</div>
	<!-- ETAPE 3 -->
	<div id="sd_step3" class="sd_step  <?php if($general_configuration>=2){?>sd_show_step<?php }?>">
		<div class="sd_step_line"></div>

		<div class="sd_step3_instruction">
			<div id="3_step_block" <?php if(Mage::getSingleton("core/session")->getData("sd_is_user") == "yes" || Mage::getSingleton("core/session")->getData("sd_is_user") == null){?> class="HIDDEN" <?php }?>>
				<p>
					1/ <a href="<?=$this->__('https://www.sarbacane.com/ws/soft-redirect.asp?key=heXmrxBEUO&com=MagentoInfo')?>" target="_blank"><?=$this->__('Download and install Sarbacane')?></a>
				</p>
				<p>2/ <?=$this->__('Create your free account')?></p>
				<p>3/ <?=$this->__('Enable the Magento extension in our extensions menu, and then fill in the following fields:')?></p>
			</div>
			<div id="1_step_block" <?php if(Mage::getSingleton("core/session")->getData("sd_is_user") == "no"){?> class="HIDDEN" <?php }?>>
				<p><?=$this->__('Enable the Magento extension in our extensions menu, and then fill in the following fields:')?></p>
			</div>
			<form autocomplete="off" action="<?= Mage::helper('adminhtml')->getUrl("*/*/*/"); ?>#sd_step" method="post">
				<div class="sd_key_container">
					<p><?=$this->__('Url')?></p>
					<input value="<?=Mage::getBaseUrl() ?>" onclick="this.select()" type="text" readonly />
				</div>
				<div class="sd_key_container">
					<p><?=$this->__('Key')?></p>
					<input value="<?=$key_for_synchronisation?>" onclick="this.select()" type="text" readonly />
				</div>
				<p class="sd_key_button_container">
					<input type="hidden" name="submit_parameter_key" value="1" /> <input type="hidden" name="form_key" value="<?=$this->getFormKey()?>" /> <input type="submit" class="sd_key_button" value="<?=$this->__('Generate a new key')?>" />
				</p>
			</form>
		</div>
		<div class="sd_step_buttons">
			<div class="sd_step_buttons_left">
				<input type="button" onclick="sdDisplayStep(2)" value="<?=$this->__('Previous')?>" />
			</div>
			<div class="sd_step3_right">
				<?=$this->__('Read more')?>, <a href="<?=$this->__('http://www.sarbacane.com/faq/extensions/configuration-plugin-magento/?utm_source=module-magento&utm_medium=plugin&utm_content=lien-sarbacane&utm_campaign=magento')?>" target="_blank"><?=$this->__('in the help section online')?></a>
			</div>
		</div>
	</div>
</div>