<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @version    2.4.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($this->helper('advancednewsletter')->showSegmentsAtCustomerRegistration() && $this->helper('advancednewsletter')->getSegmentList()->getSize() > 0): ?>
    <div class="fieldset" id="advancednewsletter-customer-reg-form">
        <h2 class="legend"><?php echo $this->helper('advancednewsletter')->__('Sign Up for Newsletter') ?></h2>
        <?php echo $this->getChildHtml('advancednewsletter.options.checkboxes'); ?>
    </div>
    <script type="text/javascript">
        (function(){
            var advancedFormElSelector = '#advancednewsletter-customer-reg-form';
            var insertAfterElSelector = '#form-validate div.fieldset';
            var advancedFormEl = $$(advancedFormElSelector).first();
            var insertAfterEl = $$(insertAfterElSelector).first();
            if (insertAfterEl) {
                if (insertAfterEl.next()) {
                    insertAfterEl.up().insertBefore(advancedFormEl, insertAfterEl.next());
                } else {
                    insertAfterEl.up().insert(advancedFormEl);
                }
            } else {
                $$(advancedFormElSelector).first().remove();
            }
        })();
    </script>
<?php endif; ?>