<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @version    2.4.7
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="col-2" id="advancednewsletter-customer-dashboard-info">
    <div class="inner-head">
        <h5><?php echo $this->__('Newsletters') ?></h5>
        <a href="<?php echo $this->getUrl('advancednewsletter/manage', array('_secure' => Mage::app()->getStore(true)->isCurrentlySecure())) ?>">
            <?php echo $this->__('Edit') ?>
        </a>
    </div>
    <p>
        <?php if( $this->getCustomerSegmentsTitles() ): ?>
            <?php echo $this->__("You are currently subscribed to ") . $this->getCustomerSegmentsTitles() ?>
        <?php else: ?>
            <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
        <?php endif; ?>
    </p>
</div>
<script type="text/javascript">
    (function(){
        var advancedNodeElSelector = '#advancednewsletter-customer-dashboard-info';
        var containerElSelector = '.dashboard .box-info .col2-set';
        var advancedNodeEl = $$(advancedNodeElSelector).first();
        var containerEl = $$(containerElSelector).first();
        if (containerEl) {
            containerEl.insert(advancedNodeEl);
        } else {
            $$(advancedNodeElSelector).first().remove();
        }
    })();
</script>