<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @version    2.5.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($this->displayLabel()): ?>
    <label for="an-segments" class="an-data"><?php echo $this->__('Select lists') ?><span class="required">*</span></label>
<?php endif; ?>
<select class="an-select an-data required-entry" name="segments_select[]" id="an-segments">
<?php foreach ($this->getSegments() as $segment): ?>
    <?php $segment->isSelected($this->getCategoryId()) == true ? $checked='selected="selected"' : $checked=''; ?>
    <option <?php echo $checked; ?> value="<?php echo $segment->getCode(); ?>"><?php echo $segment->getTitle(); ?></option>
<?php endforeach; ?>
</select>