<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @version    2.5.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $this->setBlockUniqueId($this->getBlockUniqueId() + 1) ?>
<?php if (preg_match('/^1.3/', Mage::getVersion())): ?>
<div class="box base-mini mini-newsletter an-subscribe">
    <div class="head"><h4><?php echo $this->__('Newsletter') ?></h4></div>
    <div class="block-content">
        <div class="an-buttons">
            <button id="advancednewsletter-button-<?php echo $this->getBlockUniqueId() ?>" type="submit" class="form-button-alt"><span><?php echo $this->__('Subscribe') ?></span></button>
        </div>
    </div>
</div>
<?php else: ?>
<div class="block an-subscribe">
    <div class="block-title"><strong><span><?php echo $this->__('Newsletter') ?></span></strong></div>
    <div class="block-content">
        <div class="an-buttons">
            <button id="advancednewsletter-button-<?php echo $this->getBlockUniqueId() ?>" type="submit" class="button"><span><?php echo $this->__('Subscribe') ?></span></button>
        </div>
    </div>
</div>
<?php endif; ?>

<script type="text/javascript">
    <!--
    Event.observe(window, 'load', function () {
        new Advancednewsletter($('advancednewsletter-button-<?php echo $this->getBlockUniqueId() ?>'), '<?php echo $this->getAjaxUrl() ?>');
    });
    //-->
</script>
